---
- name: "Creating {{ dev_user }} account"
  user:
    name: "{{ dev_user }}"
    shell: /bin/bash
    groups: "{{ dev_groups }}"
    append: yes
    generate_ssh_key: no
    password: "{{ lookup('password', '/dev/null') |password_hash('sha512') }}"
    update_password: on_create
  tags: 
  - file
  - url

- name: "check or change /home/{{ dev_user }}/.ssh directory"
  file:
    path: /home/{{ dev_user }}/.ssh
    state: directory
    mode: '644'
  tags: 
  - file
  - url

- name: "check or change /home/{{ dev_user }}/.ssh/authorized_keys"
  file:
    path: /home/{{ dev_user }}/.ssh/authorized_keys
    state: touch
    mode: '644'
  tags: 
  - file
  - url

- name: "get key from url"
  authorized_key:
    user: "{{ dev_user }}"
    state: present
    key: "{{ key_path }}"
  tags: 
  - url

- name: Set from file
  ansible.posix.authorized_key:
    user: "{{ dev_user }}"
    state: present
    key: "{{ lookup('file', key_path ) }}"
  tags: 
  - file
